packages:
  - apps/*
  - packages/*

allowBuilds:
  '@prisma/engines': true
  prisma: true
  '@nestjs/core': true
  '@swc/core': true
  esbuild: true
  sharp: true
  unrs-resolver: true

storeDir: .local/pnpm-store
