export enum CampaignStatus {
  DRAFT = 'DRAFT',
  GENERATING = 'GENERATING',
  PENDING_APPROVAL = 'PENDING_APPROVAL',
  APPROVED = 'APPROVED',
  PUBLISHING = 'PUBLISHING',
  PUBLISHED = 'PUBLISHED',
  PARTIALLY_PUBLISHED = 'PARTIALLY_PUBLISHED',
  FAILED = 'FAILED',
}

export enum CampaignFailureOrigin {
  GENERATION = 'GENERATION',
  PUBLICATION = 'PUBLICATION',
}

export enum GenerationFailureCode {
  GENERATION_FAILED = 'GENERATION_FAILED',
  TIMEOUT = 'TIMEOUT',
  INVALID_OUTPUT = 'INVALID_OUTPUT',
}
