export enum CampaignStatus {
  DRAFT = 'DRAFT',
  GENERATING = 'GENERATING',
  PENDING_APPROVAL = 'PENDING_APPROVAL',
  APPROVED = 'APPROVED',
  FAILED = 'FAILED',
}

export enum GenerationFailureCode {
  GENERATION_FAILED = 'GENERATION_FAILED',
  TIMEOUT = 'TIMEOUT',
  INVALID_OUTPUT = 'INVALID_OUTPUT',
}
